defaults:
  - default.yaml

train:
  dataset:
    _target_: siaug.dataloaders.VinDRDataset
    path: ${paths.data_dir}/vindr/annotations/image_labels_train_ground_truth.csv
    data_dir: ${paths.data_dir}/vindr/512
    columns:
      [
        "Aortic enlargement",
        "Atelectasis",
        "Calcification",
        "Cardiomegaly",
        "Clavicle fracture",
        "Consolidation",
        "Edema", 
        "Emphysema", 
        "Enlarged PA", 
        "ILD"    
      ]
    na_mode: null
    img_transform: ???
    txt_transform: null
    lbl_transform: null

valid:
  dataset:
    _target_: siaug.dataloaders.VinDRDataset
    path: ${paths.data_dir}/vindr/annotations/image_labels_test_ground_truth.csv
    data_dir: ${paths.data_dir}/vindr/512
    columns:
      [
        "Aortic enlargement",
        "Atelectasis",
        "Calcification",
        "Cardiomegaly",
        "Clavicle fracture",
        "Consolidation",
        "Edema", 
        "Emphysema", 
        "Enlarged PA", 
        "ILD"    
      ]
    na_mode: null
    img_transform: ???
    txt_transform: null
    lbl_transform: null
