defaults:
  - default.yaml

train:
  dataset:
    _target_: siaug.dataloaders.VinDRDataset
    path: ${paths.data_dir}/vindr/annotations/image_labels_train_ground_truth.csv
    data_dir: ${paths.data_dir}/vindr/512
    columns:
      [
        "Atelectasis",
        "Cardiomegaly",
        "Edema",
        "Rib fracture",
        "Pleural effusion",
        "Pneumonia",
        "Pneumothorax",
        "No finding",  
      ]
    na_mode: null
    img_transform: ???
    txt_transform: null
    lbl_transform: null

valid:
  dataset:
    _target_: siaug.dataloaders.VinDRDataset
    path: ${paths.data_dir}/vindr/annotations/image_labels_train_ground_truth.csv
    data_dir: ${paths.data_dir}/vindr/512
    columns:
      [
        "Atelectasis",
        "Cardiomegaly",
        "Edema",
        "Rib fracture",
        "Pleural effusion",
        "Pneumonia",
        "Pneumothorax",
        "No finding",    
      ]
    na_mode: null
    img_transform: ???
    txt_transform: null
    lbl_transform: null
